"""create initial schema

Revision ID: 29cbc6b430c4
Revises:
Create Date: 2026-09-16 12:44:36.098610
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "29cbc6b430c4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "departments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("btrim(code) <> ''", name=op.f("ck_departments_code_not_blank")),
        sa.CheckConstraint("btrim(name) <> ''", name=op.f("ck_departments_name_not_blank")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_departments")),
        sa.UniqueConstraint("code", name=op.f("uq_departments_code")),
    )
    op.create_index(
        "idx_departments_active_name", "departments", ["is_active", "name"], unique=False
    )
    op.create_table(
        "hcps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("professional_title", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("btrim(code) <> ''", name=op.f("ck_hcps_code_not_blank")),
        sa.CheckConstraint("btrim(name) <> ''", name=op.f("ck_hcps_name_not_blank")),
        sa.CheckConstraint(
            "professional_title IS NULL OR btrim(professional_title) <> ''",
            name=op.f("ck_hcps_professional_title_not_blank"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hcps")),
        sa.UniqueConstraint("code", name=op.f("uq_hcps_code")),
    )
    op.create_index("idx_hcps_active_name", "hcps", ["is_active", "name"], unique=False)
    op.create_table(
        "hospitals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("btrim(code) <> ''", name=op.f("ck_hospitals_code_not_blank")),
        sa.CheckConstraint("btrim(name) <> ''", name=op.f("ck_hospitals_name_not_blank")),
        sa.CheckConstraint("latitude BETWEEN -90 AND 90", name=op.f("ck_hospitals_latitude_range")),
        sa.CheckConstraint(
            "longitude BETWEEN -180 AND 180", name=op.f("ck_hospitals_longitude_range")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hospitals")),
        sa.UniqueConstraint("code", name=op.f("uq_hospitals_code")),
    )
    op.create_index("idx_hospitals_active_name", "hospitals", ["is_active", "name"], unique=False)
    op.create_table(
        "medical_representatives",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(code) <> ''", name=op.f("ck_medical_representatives_code_not_blank")
        ),
        sa.CheckConstraint(
            "btrim(name) <> ''", name=op.f("ck_medical_representatives_name_not_blank")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_medical_representatives")),
        sa.UniqueConstraint("code", name=op.f("uq_medical_representatives_code")),
    )
    op.create_index(
        "idx_medical_representatives_active_name",
        "medical_representatives",
        ["is_active", "name"],
        unique=False,
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("btrim(code) <> ''", name=op.f("ck_products_code_not_blank")),
        sa.CheckConstraint("btrim(name) <> ''", name=op.f("ck_products_name_not_blank")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("code", name=op.f("uq_products_code")),
    )
    op.create_index("idx_products_active_name", "products", ["is_active", "name"], unique=False)
    op.create_table(
        "hospital_departments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column("department_id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "display_name IS NULL OR btrim(display_name) <> ''",
            name=op.f("ck_hospital_departments_display_name_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_hospital_departments_department_id_departments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_hospital_departments_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hospital_departments")),
        sa.UniqueConstraint(
            "hospital_id", "department_id", name="uq_hospital_departments_hospital_department"
        ),
    )
    op.create_index(
        "idx_hospital_departments_department_id",
        "hospital_departments",
        ["department_id"],
        unique=False,
    )
    op.create_table(
        "hcp_practices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("hcp_id", sa.Uuid(), nullable=False),
        sa.Column("hospital_department_id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["hcp_id"], ["hcps.id"], name=op.f("fk_hcp_practices_hcp_id_hcps"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["hospital_department_id"],
            ["hospital_departments.id"],
            name=op.f("fk_hcp_practices_hospital_department_id_hospital_departments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hcp_practices")),
        sa.UniqueConstraint(
            "hcp_id", "hospital_department_id", name="uq_hcp_practices_hcp_department"
        ),
    )
    op.create_index(
        "idx_hcp_practices_hospital_department_id",
        "hcp_practices",
        ["hospital_department_id"],
        unique=False,
    )
    op.create_table(
        "visit_plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("mr_id", sa.Uuid(), nullable=False),
        sa.Column("hcp_practice_id", sa.Uuid(), nullable=False),
        sa.Column("planned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("mr_code_snapshot", sa.String(length=50), nullable=False),
        sa.Column("mr_name_snapshot", sa.String(length=100), nullable=False),
        sa.Column("hcp_code_snapshot", sa.String(length=50), nullable=False),
        sa.Column("hcp_name_snapshot", sa.String(length=100), nullable=False),
        sa.Column("hospital_code_snapshot", sa.String(length=50), nullable=False),
        sa.Column("hospital_name_snapshot", sa.String(length=200), nullable=False),
        sa.Column("department_code_snapshot", sa.String(length=50), nullable=False),
        sa.Column("department_name_snapshot", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(department_code_snapshot) <> ''",
            name=op.f("ck_visit_plans_department_code_snapshot_not_blank"),
        ),
        sa.CheckConstraint(
            "btrim(department_name_snapshot) <> ''",
            name=op.f("ck_visit_plans_department_name_snapshot_not_blank"),
        ),
        sa.CheckConstraint(
            "btrim(hcp_code_snapshot) <> ''",
            name=op.f("ck_visit_plans_hcp_code_snapshot_not_blank"),
        ),
        sa.CheckConstraint(
            "btrim(hcp_name_snapshot) <> ''",
            name=op.f("ck_visit_plans_hcp_name_snapshot_not_blank"),
        ),
        sa.CheckConstraint(
            "btrim(hospital_code_snapshot) <> ''",
            name=op.f("ck_visit_plans_hospital_code_snapshot_not_blank"),
        ),
        sa.CheckConstraint(
            "btrim(hospital_name_snapshot) <> ''",
            name=op.f("ck_visit_plans_hospital_name_snapshot_not_blank"),
        ),
        sa.CheckConstraint(
            "btrim(mr_code_snapshot) <> ''", name=op.f("ck_visit_plans_mr_code_snapshot_not_blank")
        ),
        sa.CheckConstraint(
            "btrim(mr_name_snapshot) <> ''", name=op.f("ck_visit_plans_mr_name_snapshot_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["hcp_practice_id"],
            ["hcp_practices.id"],
            name=op.f("fk_visit_plans_hcp_practice_id_hcp_practices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["mr_id"],
            ["medical_representatives.id"],
            name=op.f("fk_visit_plans_mr_id_medical_representatives"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_visit_plans")),
    )
    op.create_index(
        "idx_visit_plans_hcp_practice_id", "visit_plans", ["hcp_practice_id"], unique=False
    )
    op.create_index(
        "idx_visit_plans_mr_planned_at",
        "visit_plans",
        ["mr_id", sa.literal_column("planned_at DESC")],
        unique=False,
    )
    op.create_table(
        "visit_plan_products",
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("product_code_snapshot", sa.String(length=50), nullable=False),
        sa.Column("product_name_snapshot", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(product_code_snapshot) <> ''",
            name=op.f("ck_visit_plan_products_product_code_snapshot_not_blank"),
        ),
        sa.CheckConstraint(
            "btrim(product_name_snapshot) <> ''",
            name=op.f("ck_visit_plan_products_product_name_snapshot_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["visit_plans.id"],
            name=op.f("fk_visit_plan_products_plan_id_visit_plans"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_visit_plan_products_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("plan_id", "product_id", name="pk_visit_plan_products"),
    )
    op.create_index(
        "idx_visit_plan_products_product_plan",
        "visit_plan_products",
        ["product_id", "plan_id"],
        unique=False,
    )
    op.create_table(
        "visits",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("hospital_latitude_snapshot", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("hospital_longitude_snapshot", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("check_in_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("check_in_latitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("check_in_longitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("check_in_distance_meters", sa.Numeric(precision=15, scale=6), nullable=False),
        sa.Column("check_out_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("check_out_latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("check_out_longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("check_out_distance_meters", sa.Numeric(precision=15, scale=6), nullable=True),
        sa.Column(
            "duration_seconds",
            sa.Numeric(precision=18, scale=6),
            sa.Computed(
                "CASE WHEN check_out_at IS NULL THEN NULL "
                "ELSE EXTRACT(EPOCH FROM (check_out_at - check_in_at)) END",
                persisted=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(check_out_at IS NULL AND check_out_latitude IS NULL "
            "AND check_out_longitude IS NULL AND check_out_distance_meters IS NULL) OR "
            "(check_out_at IS NOT NULL AND check_out_latitude IS NOT NULL "
            "AND check_out_longitude IS NOT NULL AND check_out_distance_meters IS NOT NULL)",
            name=op.f("ck_visits_check_out_fields_complete"),
        ),
        sa.CheckConstraint(
            "check_in_distance_meters >= 0", name=op.f("ck_visits_check_in_distance_nonnegative")
        ),
        sa.CheckConstraint(
            "check_in_latitude BETWEEN -90 AND 90", name=op.f("ck_visits_check_in_latitude_range")
        ),
        sa.CheckConstraint(
            "check_in_longitude BETWEEN -180 AND 180",
            name=op.f("ck_visits_check_in_longitude_range"),
        ),
        sa.CheckConstraint(
            "check_out_at IS NULL OR check_out_at >= check_in_at",
            name=op.f("ck_visits_check_out_not_before_check_in"),
        ),
        sa.CheckConstraint(
            "check_out_distance_meters IS NULL OR check_out_distance_meters >= 0",
            name=op.f("ck_visits_check_out_distance_nonnegative"),
        ),
        sa.CheckConstraint(
            "check_out_latitude IS NULL OR check_out_latitude BETWEEN -90 AND 90",
            name=op.f("ck_visits_check_out_latitude_range"),
        ),
        sa.CheckConstraint(
            "check_out_longitude IS NULL OR check_out_longitude BETWEEN -180 AND 180",
            name=op.f("ck_visits_check_out_longitude_range"),
        ),
        sa.CheckConstraint(
            "duration_seconds IS NULL OR duration_seconds >= 0",
            name=op.f("ck_visits_duration_nonnegative"),
        ),
        sa.CheckConstraint(
            "hospital_latitude_snapshot BETWEEN -90 AND 90",
            name=op.f("ck_visits_hospital_latitude_snapshot_range"),
        ),
        sa.CheckConstraint(
            "hospital_longitude_snapshot BETWEEN -180 AND 180",
            name=op.f("ck_visits_hospital_longitude_snapshot_range"),
        ),
        sa.CheckConstraint(
            "updated_at >= created_at", name=op.f("ck_visits_updated_not_before_created")
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["visit_plans.id"],
            name=op.f("fk_visits_plan_id_visit_plans"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_visits")),
        sa.UniqueConstraint("plan_id", name="uq_visits_plan_id"),
    )
    op.create_index("idx_visits_check_in_at_id", "visits", ["check_in_at", "id"], unique=False)
    op.create_table(
        "compliance_findings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("visit_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("phase", sa.String(length=20), nullable=False),
        sa.Column("measured_value", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("threshold_value", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(code = 'CHECK_IN_LOCATION_OUT_OF_RANGE' AND phase = 'CHECK_IN' "
            "AND unit = 'METERS' AND threshold_value = 500 "
            "AND measured_value > threshold_value) OR "
            "(code = 'CHECK_OUT_LOCATION_OUT_OF_RANGE' AND phase = 'CHECK_OUT' "
            "AND unit = 'METERS' AND threshold_value = 500 "
            "AND measured_value > threshold_value) OR "
            "(code = 'DURATION_TOO_SHORT' AND phase = 'CHECK_OUT' "
            "AND unit = 'SECONDS' AND threshold_value = 300 "
            "AND measured_value < threshold_value)",
            name=op.f("ck_compliance_findings_code_semantics"),
        ),
        sa.CheckConstraint(
            "code IN ('CHECK_IN_LOCATION_OUT_OF_RANGE', "
            "'CHECK_OUT_LOCATION_OUT_OF_RANGE', 'DURATION_TOO_SHORT')",
            name=op.f("ck_compliance_findings_code_allowed"),
        ),
        sa.CheckConstraint(
            "phase IN ('CHECK_IN', 'CHECK_OUT')", name=op.f("ck_compliance_findings_phase_allowed")
        ),
        sa.CheckConstraint(
            "unit IN ('METERS', 'SECONDS')", name=op.f("ck_compliance_findings_unit_allowed")
        ),
        sa.CheckConstraint(
            "measured_value >= 0", name=op.f("ck_compliance_findings_measured_value_nonnegative")
        ),
        sa.CheckConstraint(
            "threshold_value > 0", name=op.f("ck_compliance_findings_threshold_value_positive")
        ),
        sa.ForeignKeyConstraint(
            ["visit_id"],
            ["visits.id"],
            name=op.f("fk_compliance_findings_visit_id_visits"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_compliance_findings")),
        sa.UniqueConstraint("visit_id", "code", name="uq_compliance_findings_visit_code"),
    )
    op.create_index(
        "idx_compliance_findings_code_detected_at",
        "compliance_findings",
        ["code", "detected_at"],
        unique=False,
    )
    op.create_table(
        "visit_products",
        sa.Column("visit_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("product_code_snapshot", sa.String(length=50), nullable=False),
        sa.Column("product_name_snapshot", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(product_code_snapshot) <> ''",
            name=op.f("ck_visit_products_product_code_snapshot_not_blank"),
        ),
        sa.CheckConstraint(
            "btrim(product_name_snapshot) <> ''",
            name=op.f("ck_visit_products_product_name_snapshot_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_visit_products_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["visit_id"],
            ["visits.id"],
            name=op.f("fk_visit_products_visit_id_visits"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("visit_id", "product_id", name="pk_visit_products"),
    )
    op.create_index(
        "idx_visit_products_product_visit",
        "visit_products",
        ["product_id", "visit_id"],
        unique=False,
    )
    op.create_table(
        "visit_reports",
        sa.Column("visit_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_summary", sa.Text(), nullable=False),
        sa.Column("hcp_feedback", sa.Text(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(conversation_summary) <> ''",
            name=op.f("ck_visit_reports_conversation_summary_not_blank"),
        ),
        sa.CheckConstraint(
            "btrim(hcp_feedback) <> ''", name=op.f("ck_visit_reports_hcp_feedback_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["visit_id"],
            ["visits.id"],
            name=op.f("fk_visit_reports_visit_id_visits"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("visit_id", name=op.f("pk_visit_reports")),
    )
    op.create_table(
        "academic_detailing_records",
        sa.Column("visit_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("content_summary", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(content_summary) <> ''",
            name=op.f("ck_academic_detailing_records_content_summary_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["visit_id", "product_id"],
            ["visit_products.visit_id", "visit_products.product_id"],
            name=op.f("fk_academic_detailing_records_visit_id_visit_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["visit_id"],
            ["visit_reports.visit_id"],
            name=op.f("fk_academic_detailing_records_visit_id_visit_reports"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("visit_id", "product_id", name="pk_academic_detailing_records"),
    )
    op.create_table(
        "material_distributions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("visit_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("material_code", sa.String(length=100), nullable=False),
        sa.Column("material_name", sa.String(length=200), nullable=False),
        sa.Column("quantity", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("is_compliant", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(material_code) <> ''",
            name=op.f("ck_material_distributions_material_code_not_blank"),
        ),
        sa.CheckConstraint(
            "btrim(material_name) <> ''",
            name=op.f("ck_material_distributions_material_name_not_blank"),
        ),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_material_distributions_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["visit_id", "product_id"],
            ["visit_products.visit_id", "visit_products.product_id"],
            name=op.f("fk_material_distributions_visit_id_visit_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["visit_id"],
            ["visit_reports.visit_id"],
            name=op.f("fk_material_distributions_visit_id_visit_reports"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_material_distributions")),
    )
    op.create_index(
        "idx_material_distributions_product_id",
        "material_distributions",
        ["product_id"],
        unique=False,
        postgresql_where=sa.text("product_id IS NOT NULL"),
    )
    op.create_index(
        "idx_material_distributions_visit_id", "material_distributions", ["visit_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_material_distributions_visit_id", table_name="material_distributions")
    op.drop_index(
        "idx_material_distributions_product_id",
        table_name="material_distributions",
        postgresql_where=sa.text("product_id IS NOT NULL"),
    )
    op.drop_table("material_distributions")
    op.drop_table("academic_detailing_records")
    op.drop_table("visit_reports")
    op.drop_index("idx_visit_products_product_visit", table_name="visit_products")
    op.drop_table("visit_products")
    op.drop_index("idx_compliance_findings_code_detected_at", table_name="compliance_findings")
    op.drop_table("compliance_findings")
    op.drop_index("idx_visits_check_in_at_id", table_name="visits")
    op.drop_table("visits")
    op.drop_index("idx_visit_plan_products_product_plan", table_name="visit_plan_products")
    op.drop_table("visit_plan_products")
    op.drop_index("idx_visit_plans_mr_planned_at", table_name="visit_plans")
    op.drop_index("idx_visit_plans_hcp_practice_id", table_name="visit_plans")
    op.drop_table("visit_plans")
    op.drop_index("idx_hcp_practices_hospital_department_id", table_name="hcp_practices")
    op.drop_table("hcp_practices")
    op.drop_index("idx_hospital_departments_department_id", table_name="hospital_departments")
    op.drop_table("hospital_departments")
    op.drop_index("idx_products_active_name", table_name="products")
    op.drop_table("products")
    op.drop_index("idx_medical_representatives_active_name", table_name="medical_representatives")
    op.drop_table("medical_representatives")
    op.drop_index("idx_hospitals_active_name", table_name="hospitals")
    op.drop_table("hospitals")
    op.drop_index("idx_hcps_active_name", table_name="hcps")
    op.drop_table("hcps")
    op.drop_index("idx_departments_active_name", table_name="departments")
    op.drop_table("departments")
    # ### end Alembic commands ###
